name: Build & Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: erik-skopp-deploy
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Go (for Hugo Modules)
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true

      - name: Cache Hugo modules & resources
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo
            ~/go/pkg/mod
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Set up Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Hugo Build
        run: |
          hugo mod get
          hugo mod tidy
          hugo --gc --minify --enableGitInfo

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4 